spring:
  datasource:
      url: jdbc:mysql://localhost:3306/restcrud
      username: root
      password: Patel67&
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update


server:
  port: 8080


